---
# Source: reloader/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-namespace: "{{ k8sNamespace }}"
    meta.helm.sh/release-name: "d-reloader"
  labels:
    app: d-reloader-reloader
    chart: "reloader-1.0.40"
    release: "d-reloader"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
  name: d-reloader-reloader
  namespace: {{ k8sNamespace }}
