apiVersion: v1
kind: Namespace
metadata:
  name: {{ k8sNamespace }}
  labels:
    d-monitoring/enabled: "true"

---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata: 
  name: d-reloader-scc
priority: 0
allowPrivilegedContainer: false
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
defaultAddCapabilities: []
requiredDropCapabilities: []
allowedCapabilities: []
readOnlyRootFilesystem: false
volumes:
- configMap
- emptyDir
- persistentVolumeClaim
- secret
- projected
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{ k8sNamespace }}:d-reloader-reloader